name: Laravel

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
        coverage: xdebug
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist  
      
    - name: Excecute phpcsw
      run: composer phpcs_validate 
      
    - name: Prepare the application
      run: |
        cp .env.example .env 
        php artisan key:generate
        

      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Clear Config
      run: php artisan config:clear
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: composer run-script test-ci
        


    - name: Prepare paths for SonarQube analysis
      run: |
        sed -i "s|$GITHUB_WORKSPACE|/github/workspace|g" phpunit.report.xml
        sed -i "s|$GITHUB_WORKSPACE|/github/workspace|g" phpunit.coverage.xml
        
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
